pipeline {
  agent {
    docker {
      image 'jenkinsnetcoreagent:latest'
    }
  }
  stages {
    stage('SCM') {
        steps {
      		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/shab-a88/Jenkinspipeline.git']]])
	      }
    }

    stage('Build') {
          steps {
               sh 'dotnet build "$WORKSPACE/netcoreapp/netcoreapp.csproj"'
          }
    }

    stage('Publish') {
          steps {
    	      sh 'dotnet publish "$WORKSPACE/netcoreapp/netcoreapp.csproj"'
            archiveArtifacts artifacts: 'netcoreapp/bin/Debug/netcoreapp3.1/publish/*'
          }
    }
  }
}